### ISSUE TITLE
[FR] File conversion that can retain text

### ISSUE THREAD

**Issue by Legosi13** [binarynonsense/comic-book-reader#106]
I swear, there just doesn't seem to be such a thing as a EPUB to PDF converter that doesn't take 15 centuries (or if ever) to actually convert what I want to be converted. However, I am loving the progress that's coming along with this project! I'm hoping it'd be possible for this to be possible!

**Comment by binarynonsense** [comment]
I'm not sure what you mean. Is it being able to convert text ebooks, not comic books containing just images, in EPUB format to PDF?

**Comment by Legosi13** [comment]
> I'm not sure what feature exactly you'd like to be added. Is it being able to convert ebook files (with text, images...), not just comic book files containing only images, in EPUB format to PDF?
> 
> Edit: rewrote it a little to make my question more clear.

Thanks for the response. I should've utilized better wording, but yes, being able to convert ebook files (with embedded text, images, etc.) is what I'm most interested in. 

I've tried Calibre, and other contemporary readers/converters, but all of them this your program seems to be the most comprehensive and promising.

Apologies for the vagueness/incoherence on my part.

**Comment by binarynonsense** [comment]
No problem, I thought that was what you meant but wanted to make sure.

I'm sorry but that's really out of the scope of the project. ACBR is focused on comic book files and the tools just support EPUB files containing only images because of that (there's support in the reader to display EPUB ebooks but even that, as the README says, is an experimental, extra feature that could be removed in future versions if necessary). I only added support to image-only EPUBs because I saw it was relatively easy if I only allowed files with those constrains (parsing the files' contents is much simpler) and worked with EPUB comics I had from Humble Bundle (so it felt like a useful, comic related, thing to include). 

Adding converting regular, full featured EPUBs (to PDF or other formats) to the tools I think would be, at the very least, quite a complex undertaking (right now I wouldn't know where to begin), and I need to use the time I have to work on the app to add or improve things that I feel I can do and are more related to the goals of the project (reading and converting comic books).

If at some point I think of a relatively easy way to implement and maintain it, which seems doubtful given the complexity of the issue, or find a simple and compatible library with good support to help me do it, I'll try to add this feature but, to tell you the truth, I don't see that happening in the foreseeable future so I'm afraid it's a feature ACBR won't probably have. 

Hope you understand, and thanks for taking the time to write this feature request!

**Comment by Legosi13** [comment]
> No problem, I thought that was what you meant but wanted to make sure.
> 
> I'm sorry but that's really out of the scope of the project. ACBR is focused on comic book files and the tools just support EPUB files containing only images because of that (there's support in the reader to display EPUB ebooks but even that, as the README says, is an experimental, extra feature that could be removed in future versions if necessary). And I only added support to image-only EPUBs because I saw it was relatively easy if I only allowed files with those constrains (parsing the files' contents is much simpler) and that made EPUB comics I had from Humble Bundle work (so it felt like a useful, comic related, thing to include). Edit: EPUBs weren't supported at all in the first versions, as it didn't seem like a very common format for comics.
> 
> Adding converting regular, full featured EPUBs (to PDF or other formats) to the tools I think would be, at the very least, quite a complex undertaking (right now I wouldn't know where to begin), and I need to use the time I have to work on the app to add or improve things that I feel I can do and are more related to the goals of the project (reading and converting comic books).
> 
> If at some point I think of a relatively easy way to implement and maintain it, which seems doubtful given the complexity of the issue, or find a simple and compatible library with good support to help me do it, I'll try to add this feature but, to tell you the truth, I don't see that happening in the foreseeable future so I'm afraid it's a feature ACBR won't probably have.
> 
> Hope you understand, and thanks for taking the time to write this feature request!

Not a problem! I understand that it's out of scope, and I very much appreciate the response! God bless :-)

**Comment by binarynonsense** [comment]
Thanks for your understanding. I'm closing the issue but don't hesitate to reopen it/write more if you think of something more to add.
