### ISSUE TITLE
[FR] Portable settings option

### ISSUE THREAD

**Issue by vatterspun** [binarynonsense/comic-book-reader#13]
**Current behavior**

Writes settings to _\AppData\Roaming\acbr-comic-book-reader\_

**Requested behavior** 

Having some options to keep any and all files, settings, etc. in the same folder has several advantages.  You can run it from a USB drive, encrypted volume, sync across devices (such as a network sync or cloud service).

**Comment by vatterspun** [comment]
> Right now I'm leaning towards keeping it like it is and having the portable settings as a preferences option (or maybe just by creating a portable.txt file in the same folder as I've seen some programs do)...

I'm a big proponent of portable-as-default, but I'm not your average user.  Also, the upgrade cycle is a massive problem around this topic and I don't have a good solution.  For programs that have a lot of configuration options, having to re-enter those configurations over and over again is what I'm trying to get away from.  Every time I setup a Win10 install for example, it's at least an hour of tweaks to get it to work the way I want and that's absurd.  (I know there's an import tool around this but I have issues with that as well.)

While ACBR doesn't have even 0.01% of the available configuration settings to worry about as Win10, I'd probably still stick with standard settings behavior.  Mainly because I don't want to alienate your users or confuse people with extra upgrade steps.

So yeah a menu configuration option (ideal) and/or portable.txt (also good) is great.

Thanks for being receptive to the idea.

**Comment by binarynonsense** [comment]
I've uploaded a [beta version](https://github.com/binarynonsense/comic-book-reader/releases/tag/v2.1.0-beta1) with this and a couple new other features. I don't know when/if I'll have enough time in the foreseeable future to work on some other things I want to try adding and make a proper, thoroughly tested release but managed to make some time to add this few things today and hopefully releasing a beta like this will be useful for people like you interested on trying/using some of them.

Anyway, to make the program portable you have to create a file named _portable.txt_ in the same folder as its executable. This will make it save, and read, its configuration files inside the same folder as the executable, instead of the default behavior of saving them system-wide.
