### ISSUE TITLE
Add "Show Loading"

### ISSUE THREAD

**Issue by rtritto** [binarynonsense/comic-book-reader#171]
Add "Show Loading" option to View > Layout for

![immagine](https://github.com/user-attachments/assets/d923bb2d-7efe-41c2-85b8-460f1fc59bc7)

to enable/disable the loading

**Comment by binarynonsense** [comment]
I may add this some day, didn't consider it before because I think it offers important information about what the program is doing and the small version is very unintrusive but if some users would prefer to be able to disable it (as it seems to be your case) I can do that. I don't know when I'll have the time to work on the next version (I'm currently working on other projects) so no promises as to if or when, but I'll add it to my TODO list to remember it.

**Comment by binarynonsense** [comment]
I just released a new beta, [3.7.0-beta1](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.7.0-beta1), that adds a menu entry in the 'view > layout' section to show / hide the loading indicator.

Let me know if you give it a try.

**Comment by rtritto** [comment]
Thanks, it works!

**Comment by binarynonsense** [comment]
No problem, thanks for testing it.
