### ISSUE TITLE
[FR] Epub metadata editor

### ISSUE THREAD

**Issue by nado** [binarynonsense/comic-book-reader#90]
Hi, it looks like a really neat project. I’m in the process of centralizing some of my books/comics/mangas and for some I got either epub or cbz.
Would you consider adding a basic support for **reading and editing epub metadata** the same way you support ComicInfo.xml?
I’d be really glad to be able to use only one software for the different metadata filling intented before importing my collection into Kavita.

**Comment by binarynonsense** [comment]
No promises, and it wouldn't be in the near future, as I don't know if/when I'll have the time to work on ACBR, besides small things, but sounds like something interesting to add.

Some time ago I made a very, very simple EPUB generator for ACBR (as I only needed to generate comic book files, not complex books) but didn't look that much into what can be included in the metadata of an EPUB file. From a first quick search, feels like version 3.3 of the standard (the first one I found containing clear information about metadata) is relatively straightforward and there are a bunch of elements to read from or include the metadata into (dc:language | dc:title | dc:contributor | dc:coverage | dc:creator | dc:date | dc:description | dc:format | dc:publisher | dc:relation | dc:rights | dc:source | dc:subject | dc:type) so that seems encouraging and a good point to start from, but I'm not so sure about previous versions of the EPUB standard. What I found from this quick search about 2.0, for example, looked a bit muddier... if things are too different or too many options are possible it would make me think twice about trying to implement an editor. It's a topic I know nothing about so I'd need to do more research about it first.

Anyway, I'd like to at least research it and try implementing a metadata reading and, if possible, editing tool, so I'll add it to my TODO list of things to look into some day.

Thanks for the suggestion!

**Comment by binarynonsense** [comment]
Better late than never, I just released a new beta version, [3.6.0-beta1](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.6.0-beta1), that adds PDF and EPUB metadata editors. They can be accessed the same way as the ComicInfo.xml one, from the file properties window.

They still needs some more testing but so far they seem to work fine, let me know if you give it a try.
