### ISSUE TITLE
[Bug] Increase instead of decrease in file size after conversion

### ISSUE THREAD

**Issue by UPSA007** [binarynonsense/comic-book-reader#95]
Hey I converted a cbz into an epub with 90% image quality. The original cbz was 588 pages witha file size of 240 MB and the converted epub was 329 MB. I thought there might be some inefficiency with the epub code. So i converted original cbz with same setting into a CBZ and got the same result. Thought I should let you know.
![Original Page 047](https://github.com/binarynonsense/comic-book-reader/assets/93215911/2df0616e-aa4e-4085-a49b-fc61d81a4bf3)
![Original Page 033](https://github.com/binarynonsense/comic-book-reader/assets/93215911/b84f85c6-40f3-44dc-afb2-ba547f8e83ca)
![Converted Page 047](https://github.com/binarynonsense/comic-book-reader/assets/93215911/23b23061-29c6-46da-88c3-425defe05051)
![Converted Page 033](https://github.com/binarynonsense/comic-book-reader/assets/93215911/ec09ba3a-ff70-4ddb-a030-7dc4c0da0eec)

**Comment by binarynonsense** [comment]
I don't think this is a bug. 

A 90% image quality value doesn't mean that the output image will be 90% smaller or have 90% less 'quality' than the input one. It refers to the quality setting passed to the image conversion library when creating a file with the selected format, in this case jpg. As far as I understand it, when compressing a jpg image, some of the data for that image is discarded, and the quality level value sets how much. A lower level will make smaller images but less faithful to the original. 

In your case, maybe the original was created with a lower quality level than 90% or the library used to create it was provided different values for some of the conversion [parameters](https://sharp.pixelplumbing.com/api-output#jpeg) (I use the default values for most of them except for the ones you can set in the UI, as I don't want to overcomplicate things).

Anyway, I don't think there's much I can do to change this, as I just pass the input image to the image library with the given options (size %, quality and format), and the result is what it gives me.

**Comment by binarynonsense** [comment]
Made some edits to my previous answer to try to explain my thoughts more clearly :)

**Comment by UPSA007** [comment]
Just out of curiosity what jpeg encoder library do you use - the default one or mozjpeg? If I have to make a guess, that might be causing this. Btw I'm in no way an expert so just an  blind guess😅.

**Comment by binarynonsense** [comment]
I use the defaults for everything except quality, so no mozjpeg (which would make images smaller but take more time, if I'm not wrong).

Maybe I could add more format specific options in a future version... I didn't want to complicate things too much for most users but I could add a checkbox to use mozjpeg in the advanced options or next to the image quality slider only when forcing JPG as the output image format.

**Comment by UPSA007** [comment]
That will be a nifty feature for power users I'm sure. Anyways It is pretty good in this current form though. I recently used to compress a bunch of stuff where the upload limit was 120kb or less each. Used to use Photoshop before. Saved a bunch of time.

**Comment by binarynonsense** [comment]
Glad you find the tool useful. I'll add the inclusion of more format conversion options (at least the mozjpeg one, as it sounds useful and easy to add) to my TODO list to at least think about it, make some tests... when I can and have the time (not sure when that will be).

**Comment by binarynonsense** [comment]
I've just uploaded a [new beta (v3.3.3-beta5)](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.3.3-beta5) that removes the generic/confusing image quality setting from the tools' options and adds a separated 'quality' setting for each image format, with appropriate defaults for each one, to the advanced settings. Also, there's now a new 'JPG: mozjpeg' setting in the advanced options to enable mozjpeg encoding for JPGs (from my first tests, it takes longer but creates smaller files, so it may definitely be useful in some cases).

**Comment by UPSA007** [comment]
This is great. Working perfectly. 
But a few tiny things -- 
1. That mozjpeg checkbox is really easy to miss. Can you make it into a toggle switch?
2. Conversion is pretty slow in general because it only uses a single core. Can you make it use multiple cores (maybe even CUDA cores of GPUS).
3. As I may have told you earlier that in an academic setup we use the image converter quite a lot. Can you include a shortcut to launch it directly?
And finally  THANK YOU FOR ALL OF YOU GREAT WORK.

**Comment by binarynonsense** [comment]
- Yes, it's a bit small and with the default being unchecked I see how it may not be obvious what it is, I didn't have much time to add it so I used the easiest thing I already had a style for, a simple checkbox. I may need to create some on/off switches at some point for these type of things.
- I haven't looked into this at all but for the easiest way to improve this I depend on what the image library I use offers. I doubt CUDA is an option. From what I quickly found this is the only thing related to concurrency: https://sharp.pixelplumbing.com/api-utility#concurrency If I understand it correctly it should already be using a thread per core, unless you are using Linux under some circumstances. The hardest way would be to try to separate the images in groups and maybe use multiple workers/forks... haven't done anything like this with javascript/node/electron but that would probably make things quite more complicated and maybe not always be quicker, maybe even slower, depending on how I implement it and how many images are being converted due to the overheads... it's a bit of a rabbit hole :) I'll add it to my TODO list to think about/test, but I don't know when I'll have the time.
- You should already be able to do that, here are the currently available command line options: https://github.com/binarynonsense/comic-book-reader/wiki/Command-Line-Arguments

**Comment by UPSA007** [comment]
Thank You. Much appreciate your work.
P.S here is my Facebook.
https://pastebin.com/48VBzuLK
