### ISSUE TITLE
Path problem when converting PDF

### ISSUE THREAD

**Issue by ala2005** [binarynonsense/comic-book-reader#96]
On Windows 10 using ACBR version 3.3.2 a PDF cannot be converted if the path starts with the hashtag sign. The error message is attached.
![err](https://github.com/binarynonsense/comic-book-reader/assets/84496911/8d6b8f38-1f01-448a-963d-44a269e1c258)

**Comment by binarynonsense** [comment]
Thanks for the bug report!

I got a similar report by email not long ago but haven't been able to look into it so far. I'll paste here the reply I wrote: 

I'll add this to my TODO list to make some tests to try to reproduce it when I have the time to work on the program (don't know when that'll be). Seems strange that it only happens with PDFs, which makes me think it may be a bug/problem in the PDF library I use... if that's the case I'm not sure I'll be able to fix it (until they release a version without it) but if it's something in my code I'll do my best to find the cause and make it work if I can.

**Comment by trzyglow** [comment]
@ala2005 Have you tried the 3.3.3 beta?
Tested on Win11 (using the beta version) myself and couldn't replicate the bug.

**Comment by binarynonsense** [comment]
If the problem is with the PDF library, using 3.3.2 or 3.3.3-beta1 shouldn't make a difference, as that library's version is the same in both... but the fact that it doesn't happen to everyone, or maybe only in win 10 and not win 11, is a bit strange so now I'm not so sure as to what's the cause. 

I don't have a computer with Win11, so I can't check if the OS is important, but at least I can check if I can reproduce it in one with Win10 (and Linux), that would be helpful.

**Comment by binarynonsense** [comment]
Ok, I had some time to make some quick tests and I've been able to reproduce the bug in Windows 10 and Linux and it not only happens if the path starts with #, I think it happens with any path that contains # anywhere... :(

The good things are that I can reproduce it (so it's easier for me to test possible solutions) and that it only happens to PDF inputs (tried a cbz and worked fine). 

The bad things are that it not only happens with paths starting with # (which seemed like a relatively uncommon situation and easily avoidable) and that if, as I said originally, it's a bug in the PDF library I'm not sure I'll be able to fix it until they release a version without it (but I'm still not sure of the cause, it's just a possibility).

Also, the fact that it worked fine on Win 11 for @trzyglow is now even more confusing :) If it is a problem with how I feed the path to the library (maybe I need to check for and escape the hashtags/special characters, although cbz paths work fine ??) I'd think it should break in both 10 and 11... and if it's a problem with the library itself I'd think something similar (especially given that it fails on Linux too).

**Comment by binarynonsense** [comment]
I think I've managed to fix the bug. As I suspected it was a problem with how the pdf library (pdf.js) treated the input path. I found a brief comment in some open issue in another repository mentioning it may be parsing the input path looking for patterns like "#page=2" and breaking if they are used anywhere else so I tried encoding the hashtags as "%23" before passing the path to the library to 'fool' it. This seemed to fix all the issues for me on Windows 10 and Linux (I still can't figure out why @trzyglow couldn't reproduce the bug, as this should affect everyone as I understand it, but as long as it works... :)).

I've released [a new beta (3.3.3-beta2)](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.3.3-beta2) with the changes I made. Please, give it a try and let me know if things now work (I didn't have much time to make it and test it but I'm hopeful).

**Comment by ala2005** [comment]
The issue is fixed, I was able to convert a pdf from the path **c:\\# someDir**,  **c:\\temp\\#someOther** also worked well. (using Windows 10)

Thanks! :)

**Comment by binarynonsense** [comment]
No problem, glad I managed to figure it out. And thank you again for taking the time to report the bug!

PS: Some minutes before you replied I deleted the first beta I had uploaded (3.3.3-beta2) and uploaded a new one (3.3.3-beta3) to fix an issue with it (I was only replacing the first occurrence of a hashtag, so multiple hashtags would still break things). I thought no one had downloaded it yet but wanted to let you know just in case you did and want to update to the newest one.
